// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SWIA.Models;

#nullable disable

namespace SWIA.Migrations
{
    [DbContext(typeof(TreeDbContext))]
    partial class TreeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SWIA.Models.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biome")
                        .HasColumnType("text");

                    b.Property<string>("CommonName")
                        .HasColumnType("text");

                    b.Property<string>("CrownShape")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<string>("FlowerColor")
                        .HasColumnType("text");

                    b.Property<string>("FruitType")
                        .HasColumnType("text");

                    b.Property<bool?>("HasFlower")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasFruit")
                        .HasColumnType("boolean");

                    b.Property<string>("LeafArrangement")
                        .HasColumnType("text");

                    b.Property<string>("LeafFormat")
                        .HasColumnType("text");

                    b.Property<string>("LeafMargin")
                        .HasColumnType("text");

                    b.Property<string>("LeafType")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrunkType")
                        .HasColumnType("text");

                    b.Property<string>("WoodType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trees");
                });
#pragma warning restore 612, 618
        }
    }
}
